# Generated by Django 3.1.1 on 1979-12-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_developers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='username',
            new_name='email',
        ),
    ]
