# Generated by Django 3.1.1 on 2020-10-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_19800101_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('downloads', models.IntegerField()),
                ('language', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('uploader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.developers')),
            ],
        ),
    ]
