# Generated by Django 3.1.1 on 2020-10-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201021_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
