# Generated by Django 3.1.1 on 2020-10-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_projects_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='uname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
