# Generated by Django 3.1.1 on 2020-10-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_developers_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=355)),
                ('code', models.TextField(blank=True)),
                ('language', models.CharField(max_length=155)),
                ('likes', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
