# Generated by Django 3.1.1 on 2020-11-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_questions_asker_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('poster_id', models.IntegerField()),
                ('job_description', models.TextField()),
                ('location', models.TextField()),
                ('skills_needed', models.CharField(max_length=500)),
                ('job_situation', models.CharField(max_length=155)),
            ],
        ),
    ]
