# Generated by Django 3.1.1 on 2021-02-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='views',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
