# Generated by Django 3.1.1 on 2021-03-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_language_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
