# Generated by Django 3.1.1 on 2021-04-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210322_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.language'),
        ),
    ]
