# Generated by Django 3.1.1 on 2021-04-01 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210401_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.language'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='language',
            field=models.CharField(max_length=155),
        ),
    ]
