# Generated by Django 3.1.1 on 2021-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210402_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
