# Generated by Django 3.1.1 on 2021-04-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20210402_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
