# Generated by Django 3.1.1 on 2021-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20210402_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='photo',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
