# Generated by Django 3.1.1 on 2021-04-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_projects_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developers',
            name='photo',
        ),
    ]
