# Generated by Django 3.1.1 on 2021-04-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_questions_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('date', models.CharField(max_length=50)),
                ('answer', models.TextField(blank=True)),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.developers')),
            ],
        ),
    ]
