# Generated by Django 3.1.1 on 2021-04-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commentor',
            field=models.IntegerField(),
        ),
    ]
