# Generated by Django 3.1.1 on 2021-04-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20210419_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
