# Generated by Django 3.1.1 on 2021-04-19 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_comments_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
