# Generated by Django 3.1.1 on 2021-04-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_delete_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('reply', models.TextField()),
            ],
        ),
    ]
