# Generated by Django 3.1.1 on 2021-04-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20210422_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='more',
            field=models.TextField(blank=True),
        ),
    ]
