# Generated by Django 3.1.1 on 2021-05-24 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_frameworks_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
