# Generated by Django 3.1.1 on 2021-06-01 07:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210526_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
