# Generated by Django 3.1.1 on 2021-06-02 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_replies_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='likes',
            new_name='views',
        ),
    ]
