# Generated by Django 3.1.1 on 2021-06-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210602_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='aboutme',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='developers',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
