# Generated by Django 3.1.1 on 2021-06-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210602_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='developers',
            name='expertise',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
