# Generated by Django 3.1.1 on 2021-06-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_developers_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_category',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
