# Generated by Django 3.1.1 on 2021-06-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20210606_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developers',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developers',
            name='expertise',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='frameworks',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='language',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='language',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
