# Generated by Django 3.1.1 on 2021-06-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210606_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
