# Generated by Django 3.1.1 on 2021-06-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20210606_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='status',
        ),
    ]
