# Generated by Django 3.1.1 on 2021-06-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_questions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
            ],
        ),
    ]
