# Generated by Django 3.1.1 on 2021-06-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_users_device_total_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_device',
            name='total_users',
            field=models.IntegerField(),
        ),
    ]
