# Generated by Django 3.1.1 on 2021-06-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_auto_20210615_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_device',
            name='total_users',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
