# Generated by Django 3.1.1 on 2021-06-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_auto_20210615_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yearly_Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
    ]
