# Generated by Django 3.1.1 on 2021-06-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0057_yearly_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearly_visitors',
            name='total_visitors',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
