# Generated by Django 3.1.1 on 2021-06-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_yearly_visitors_total_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Unanswered'),
        ),
        migrations.AlterField(
            model_name='yearly_visitors',
            name='total_visitors',
            field=models.IntegerField(),
        ),
    ]
