# Generated by Django 3.1.1 on 2021-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20210618_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='answer',
        ),
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='replies',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
