# Generated by Django 3.1.1 on 2021-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_auto_20210618_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
