# Generated by Django 3.1.1 on 2021-06-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_comments_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
