# Generated by Django 3.1.1 on 2021-06-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_auto_20210622_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
