# Generated by Django 3.1.1 on 2021-07-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0063_auto_20210622_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=255)),
                ('notified_id', models.IntegerField()),
                ('notification_category', models.TextField()),
            ],
        ),
    ]
