# Generated by Django 3.1.1 on 2021-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0064_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification_category',
            field=models.TextField(null=True),
        ),
    ]
