# Generated by Django 3.1.1 on 2021-07-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0065_auto_20210707_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
