# Generated by Django 3.1.1 on 2021-07-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_auto_20210708_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_device',
            name='device_name',
            field=models.CharField(max_length=255),
        ),
    ]
