# Generated by Django 3.1.1 on 2021-08-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_auto_20210730_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_device',
            name='total_users',
            field=models.IntegerField(),
        ),
    ]
