# Generated by Django 3.1.1 on 2021-08-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0069_auto_20210804_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
