# Generated by Django 3.1.1 on 2021-08-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0070_auto_20210812_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='rate',
            field=models.IntegerField(blank=True),
        ),
    ]
