# Generated by Django 3.1.1 on 2021-09-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0072_projects_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='resume',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
