# Generated by Django 3.1.1 on 2021-09-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_projects_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfname', models.CharField(max_length=255)),
                ('time_uploaded', models.DateTimeField()),
                ('expiraton', models.DateTimeField()),
            ],
        ),
    ]
