# Generated by Django 3.1.1 on 2021-09-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_temppdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temppdf',
            name='pdfname',
            field=models.FileField(upload_to='media/'),
        ),
    ]
