# Generated by Django 3.1.1 on 2021-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20210903_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=500)),
            ],
        ),
    ]
