# Generated by Django 3.1.1 on 2021-09-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0078_useractivitylogs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylogs',
            name='admin_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
