# Generated by Django 3.1.1 on 2020-10-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='category',
        ),
    ]
