# Generated by Django 3.1.1 on 2020-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_projects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='asker_id',
            field=models.IntegerField(null=True),
        ),
    ]
