# Generated by Django 3.1.1 on 2021-02-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_projects_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='comments',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
