# Generated by Django 3.1.1 on 2021-02-10 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_questions_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
